services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-backend
    network_mode: host
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=8050
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_URL=${API_URL:-http://localhost:8050}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
    restart: unless-stopped
